language: node_js
node_js:
- lts/*
cache: yarn
jobs:
  include:
  - name: Lint
    script: yarn lint
  - name: Unit Test
    script: yarn test
  - name: Cucumber
    script: docker-compose run cucumber yarn cucumber
  - name: Docs
    script: ./docs.sh
    deploy:
      provider: pages:git
      local_dir: docs
      fqdn: mock-cmdr.js.org
      edge: true
      on:
        branch: master
      token:
        secure: "YH6QE4sPdu79lWhKHzXY+IMnnn9er183vDyqlMmN1iJA/gaMkLhkr7+WzO8NtU0Mqvv78Nkmzif7CfrO59Ei873sql4abOZPt93ZkGPln4Jdzj0ghFRu+XwN+ClikiP1DKNdFPyvDLqCj/VpajjwNftnkAYM4GXa/bp5XPSfszyEUcZGWlmC0g3YYCCrRz9niJp3VWC480g/AVmgMZjAxMY6yuBLRwU5A3EoExkzCp0SW2qXytN/1R4G1JffR1V/1DqTNBg0suljlmexra1RTIYRKZSwkCm7F1DAdbftF/zug5S/6EHRzwsCLtaGbUU7IkVfZyIQWjafz710HXlepca0leTbo56JAmSCDKDcmSf62S3Nmu8dGIeW4ItL/5twddrhSoZFl9P6NowoO0fi1ny8A/fRBcHpcVo2lDj5MfVxB7GUFUtFvXKiM9eFJL8xWuFv63qnjkQ8J51DKEi3PDGpFSE04ntjCkdw1qJsV7ga+yMlpP/aI4wqLrBIXoZ59eUN8hvjccPQEtjMblJBI/H9AEqNB4FsZcQorv3JHX1lfPnK5OI3GpUiXy5GB+SQ1n51KODeMoxEjLI+X+9/sanxCNVvOYjKR83pHzihE1edK6+uHhDIWJD6iggfFrQvmXiokH6M2JlZ7z5wWMhxQygZT2ARedyvabUj1Xb5tcE="
deploy:
  provider: npm
  email: nathan@ncjones.com
  api_key:
    secure: QdAnTrKeDRUfTQCltb/S5IeaKLqfK3yJiw/6mK4lytVTQtd78XMdryBUZrX2NSX03G4XWkzNW56g5wRh0R0sh1kZJakAbf+ULETkN43o2U2ULnOQgzx5VLqSdeiJueliyLs3c+Pi5p3YKD7VeuWKuVQeAkLk6CS2moyi3aZqo7GuMqyLpQAi3fRjj8ANey8fOCpeW8gYMRq1rP5DN1tH3533FPrI+RvoDRV4uy0cVbnm9OnmHIcynMQmiBUxoynRHO+/JC/hcr/YdANXHMrPpk2rIG6K2/CYFTdKH0LDmiJRYWqLOjrx55FBpWfZ7nnIpyb+L6L73vCxT9jPRBmvrl+kqN/nFkGNG/jZHuMSfAVhTJeycc5VFBa019ksTAHyPwf2MQV+7DMfXCWDsMwzMtSq2LHH8C4Qx047R/ndhxWtWJDD0uh5AjcIZBXlSrtv/lhRekNpVazZXwSQrraIa22ytGPRontXF15t8aNBmsVlNKZ54qAV5zPQd2kxvTgmw8PiJGCxG7uuJLRh9L5V407mGJbGC/KwvWpxkpdAeVsRonTqijgawath7VnymYVJFNsEdNgcafpaKJbaN/ryArcbUKHQTgtEVrhJ40tZF/o6/P5c4UsSn+T7LQmUEsIj03q9H4H0sY308BGBl4oY0J0AvUfeq6THbtdxW/49UDU=
  on:
    tags: true
    repo: ncjones/mock-cmdr
