language: node_js
node_js:
  - lts/*
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - stage: Prep
      name: CI Info
      script: scripts/ci-info.sh

    - stage: Test
      name: Lint
      script: scripts/ci-lint.sh

    - name: Unit Test
      script: scripts/ci-test.sh

    - name: Cucumber
      script: scripts/ci-cucumber.sh
