language: node_js
node_js:
  - lts/*
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:

    - name: Lint
      script: yarn lint

    - name: Unit Test
      script: yarn test

    - name: Cucumber
      script: scripts/ci-cucumber.sh
