version: "3"
services:

  wiremock:
    init: true
    image: wiremock/wiremock

  cucumber:
    build: .
    init: true
    depends_on: [ wiremock ]
    working_dir: /work
    volumes: [ .:/work ]
    command:
      - bash
      - -c
      - |
        yarn wait-on tcp:wiremock:8080 &&
        echo "
        Skipping Cucumber. To execute Cucumber tests, run:
        docker-compose run cucumber yarn cucumber"
