version: "3"
services:

  script:
    init: true
    build: .
    working_dir: /work
    volumes: [ .:/work, yarn-cache:/root/.yarn/berry/cache, node-modules:/work/node_modules  ]

  mitmproxy:
    init: true
    image: mitmproxy/mitmproxy:10.1.5
    command: mitmweb
    ports: [ "8081:8081" ]
    volumes: [ ./mitmproxy:/home/mitmproxy/.mitmproxy ]

  cucumber:
    volumes: [ .:/work, yarn-cache:/root/.yarn/berry/cache, node-modules:/work/node_modules  ]
    depends_on: [ mitmproxy ]
    environment:
      - http_proxy=http://mitmproxy:8080
      - https_proxy=http://mitmproxy:8080
      - no_proxy=yarnpkg.com,npmjs.com
      - NODE_EXTRA_CA_CERTS=/work/mitmproxy/mitmproxy-ca-cert.pem

volumes:
  node-modules:
  yarn-cache:
