version: "3"
services:
  mitmproxy:
    image: mitmproxy/mitmproxy:4.0.4
    command: mitmweb
    ports:
      - "8081:8081"
    volumes:
      - ./mitmproxy:/home/mitmproxy/.mitmproxy
  cucumber:
    environment:
      - http_proxy=http://mitmproxy:8080
      - https_proxy=http://mitmproxy:8080
      - no_proxy=yarnpkg.com,npmjs.com
      - NODE_EXTRA_CA_CERTS=/work/mitmproxy/mitmproxy-ca-cert.pem
