on:
  push: { tags: [ 'v*' ] }

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: corepack enable
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: yarn
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --immutable
      - run: scripts/version-tag-validate.js ${{ github.ref }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
